name: Deploy to Firebase

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing the dependencies
        run: yarn install
      - name: Next.js & server build
        run: yarn build
      - name: Install firebase tools
        run: sudo npm i -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
